# Generated by Django 4.2.25 on 2025-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ancho_cm', models.IntegerField()),
                ('alto_cm', models.IntegerField()),
                ('profundidad_cm', models.IntegerField()),
                ('cdr_file', models.FileField(upload_to='cdr_files/')),
            ],
        ),
    ]
