# Generated by Django 4.2.25 on 2025-10-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ancho_cm', models.IntegerField()),
                ('alto_cm', models.IntegerField()),
                ('profundidad_cm', models.IntegerField()),
                ('archivo_cdr', models.FileField(upload_to='cdr_files/')),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
    ]
