# Generated by Django 4.2.25 on 2025-10-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0002_caja_delete_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='caja',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='nombre',
        ),
        migrations.AddField(
            model_name='caja',
            name='referencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referencias.referencia'),
            preserve_default=False,
        ),
    ]
