# Generated by Django 4.2.25 on 2025-10-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0003_referencia_remove_caja_foto_remove_caja_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='alto_2d_cm',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='ancho_2d_cm',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
