# Generated by Django 4.2.25 on 2025-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0004_caja_alto_2d_cm_caja_ancho_2d_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
