# Generated by Django 4.2.25 on 2025-11-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0005_caja_archivo_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='alto_2d_cm',
            new_name='alto_2d_mm',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='ancho_2d_cm',
            new_name='ancho_2d_mm',
        ),
    ]
